# Generated by Django 4.1 on 2022-09-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_event_params_alter_event_requesturi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="params",
            field=models.JSONField(default={}, verbose_name="params"),
        ),
    ]
