# Generated by Django 4.1 on 2022-09-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_event_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="params",
            field=models.JSONField(default=dict, verbose_name="params"),
        ),
    ]
