# Generated by Django 4.1 on 2022-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_event_datetime_alter_event_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="datetime",
            field=models.CharField(max_length=200),
        ),
    ]
